### PR TITLE
- fixing build error on continuous integration

### PR DESCRIPTION
**Pull request by juchem**
- disabling continuous integration for clang 4.0
- adding continuous integration for clang 5

### CODE REVIEW

**Comment by juchem** [comment]
@yfeldblum this should fix the build error on some clang flavors. I've checked on my own fork to make sure it works, but let's wait for contbuild on the PR to be sure, though.

**Comment by yfeldblum** [comment]
Nice!

**Comment by elsteveogrande** [comment]
README.md may need an update, under Requirements: https://github.com/facebook/fatal (the list of tested-with compilers) :)

**Comment by juchem** [comment]
Good point, it should be part of this diff. I'll update.

**Comment by juchem** [comment]
Btw, to get the information out there: if you see clang complain about not
finding `gets` (just happened to be the first symbol it complained about I
guess) it's because:
1. It's using libstdc++; and
2. The libstdc++ version on the system is too old.

I've noticed it from the path of the file, it pointed to GCC 4.8 era
headers. Upgrading to GCC 6 fixed it - even though we're building with
clang since GCC brings the standard library among its dependencies.

**Pull request closed without merging**
