### PR TITLE
removing deprecated headers from `numerics.h`

### PR DESCRIPTION
**Pull request by juchem**

### CODE REVIEW

**Comment by yfeldblum** [comment]
This is a stack of 5 separate commits. GH->Phab syncing doesn't handle that. Want to split this into multiple PRs?

**Comment by juchem** [comment]
Yeah, no worries.

**Comment by juchem** [comment]
Will likely have to rebase as the PRs get in, but I'm fine with it if you are.

**Comment by juchem** [comment]
split into multiple PRs
this PR now depends on #82, #83, #84 and #85

**Comment by yfeldblum** [comment]
Internal changes:
* Whitespace changes to fit within the 80-column ruler.
* Use `bool_constant` from `fatal/type/scalar.h` to fit within the 80-column ruler.

**Pull request closed without merging**
