### PR TITLE
fixing to/from string conversion for tests

### PR DESCRIPTION
**Pull request by juchem**

### CODE REVIEW

**Comment by yfeldblum** [comment]
Is this missing a relevant include?

**Comment by juchem** [comment]
May be stacked on one of the other PRs. I haven't found a good workflow for
stacked PRs so far.

**Comment by yfeldblum** [comment]
This has an extra change to `fatal/type/search.h`.

**Comment by yfeldblum** [comment]
Internally:
* Adding an overload over `tag<std::string>`.

**Pull request closed without merging**
